// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: gamepacket.proto

package gamepacket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GamePacket struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Seq                  uint32                 `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	HandshakeRequest     *HandshakeRequest      `protobuf:"bytes,2,opt,name=HandshakeRequest,proto3" json:"HandshakeRequest,omitempty"`
	HandshakeResponse    *HandshakeResponse     `protobuf:"bytes,3,opt,name=HandshakeResponse,proto3" json:"HandshakeResponse,omitempty"`
	Heartbeat            *Heartbeat             `protobuf:"bytes,4,opt,name=Heartbeat,proto3" json:"Heartbeat,omitempty"`
	HeartbeatAck         *HeartbeatAck          `protobuf:"bytes,5,opt,name=HeartbeatAck,proto3" json:"HeartbeatAck,omitempty"`
	ClientPosition       *ClientPosition        `protobuf:"bytes,6,opt,name=ClientPosition,proto3" json:"ClientPosition,omitempty"`
	LobbyJoinBroadcast   *LobbyJoinBroadcast    `protobuf:"bytes,7,opt,name=LobbyJoinBroadcast,proto3" json:"LobbyJoinBroadcast,omitempty"`
	ClientLobbyPosition  *ClientLobbyPosition   `protobuf:"bytes,8,opt,name=ClientLobbyPosition,proto3" json:"ClientLobbyPosition,omitempty"`
	UsernamePrompt       *UsernamePrompt        `protobuf:"bytes,9,opt,name=UsernamePrompt,proto3" json:"UsernamePrompt,omitempty"`
	UsernameSubmission   *UsernameSubmission    `protobuf:"bytes,10,opt,name=UsernameSubmission,proto3" json:"UsernameSubmission,omitempty"`
	UsernameResponse     *UsernameResponse      `protobuf:"bytes,11,opt,name=UsernameResponse,proto3" json:"UsernameResponse,omitempty"`
	ReconnectionRequest  *ReconnectionRequest   `protobuf:"bytes,12,opt,name=ReconnectionRequest,proto3" json:"ReconnectionRequest,omitempty"`
	ReconnectionResponse *ReconnectionResponse  `protobuf:"bytes,13,opt,name=ReconnectionResponse,proto3" json:"ReconnectionResponse,omitempty"`
	ServerStatus         *ServerStatus          `protobuf:"bytes,99,opt,name=ServerStatus,proto3" json:"ServerStatus,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GamePacket) Reset() {
	*x = GamePacket{}
	mi := &file_gamepacket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePacket) ProtoMessage() {}

func (x *GamePacket) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePacket.ProtoReflect.Descriptor instead.
func (*GamePacket) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{0}
}

func (x *GamePacket) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GamePacket) GetHandshakeRequest() *HandshakeRequest {
	if x != nil {
		return x.HandshakeRequest
	}
	return nil
}

func (x *GamePacket) GetHandshakeResponse() *HandshakeResponse {
	if x != nil {
		return x.HandshakeResponse
	}
	return nil
}

func (x *GamePacket) GetHeartbeat() *Heartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

func (x *GamePacket) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		return x.HeartbeatAck
	}
	return nil
}

func (x *GamePacket) GetClientPosition() *ClientPosition {
	if x != nil {
		return x.ClientPosition
	}
	return nil
}

func (x *GamePacket) GetLobbyJoinBroadcast() *LobbyJoinBroadcast {
	if x != nil {
		return x.LobbyJoinBroadcast
	}
	return nil
}

func (x *GamePacket) GetClientLobbyPosition() *ClientLobbyPosition {
	if x != nil {
		return x.ClientLobbyPosition
	}
	return nil
}

func (x *GamePacket) GetUsernamePrompt() *UsernamePrompt {
	if x != nil {
		return x.UsernamePrompt
	}
	return nil
}

func (x *GamePacket) GetUsernameSubmission() *UsernameSubmission {
	if x != nil {
		return x.UsernameSubmission
	}
	return nil
}

func (x *GamePacket) GetUsernameResponse() *UsernameResponse {
	if x != nil {
		return x.UsernameResponse
	}
	return nil
}

func (x *GamePacket) GetReconnectionRequest() *ReconnectionRequest {
	if x != nil {
		return x.ReconnectionRequest
	}
	return nil
}

func (x *GamePacket) GetReconnectionResponse() *ReconnectionResponse {
	if x != nil {
		return x.ReconnectionResponse
	}
	return nil
}

func (x *GamePacket) GetServerStatus() *ServerStatus {
	if x != nil {
		return x.ServerStatus
	}
	return nil
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    string                 `protobuf:"bytes,1,opt,name=clientName,proto3" json:"clientName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_gamepacket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateId     string                 `protobuf:"bytes,1,opt,name=privateId,proto3" json:"privateId,omitempty"`
	PublicId      string                 `protobuf:"bytes,2,opt,name=publicId,proto3" json:"publicId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_gamepacket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetPrivateId() string {
	if x != nil {
		return x.PrivateId
	}
	return ""
}

func (x *HandshakeResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type UsernamePrompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernamePrompt) Reset() {
	*x = UsernamePrompt{}
	mi := &file_gamepacket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernamePrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernamePrompt) ProtoMessage() {}

func (x *UsernamePrompt) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernamePrompt.ProtoReflect.Descriptor instead.
func (*UsernamePrompt) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{3}
}

func (x *UsernamePrompt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UsernameSubmission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernameSubmission) Reset() {
	*x = UsernameSubmission{}
	mi := &file_gamepacket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernameSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameSubmission) ProtoMessage() {}

func (x *UsernameSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameSubmission.ProtoReflect.Descriptor instead.
func (*UsernameSubmission) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{4}
}

func (x *UsernameSubmission) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	IsAccepted    bool                   `protobuf:"varint,2,opt,name=isAccepted,proto3" json:"isAccepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Suggestions   []string               `protobuf:"bytes,4,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernameResponse) Reset() {
	*x = UsernameResponse{}
	mi := &file_gamepacket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameResponse) ProtoMessage() {}

func (x *UsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameResponse.ProtoReflect.Descriptor instead.
func (*UsernameResponse) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{5}
}

func (x *UsernameResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsernameResponse) GetIsAccepted() bool {
	if x != nil {
		return x.IsAccepted
	}
	return false
}

func (x *UsernameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UsernameResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type ReconnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectionRequest) Reset() {
	*x = ReconnectionRequest{}
	mi := &file_gamepacket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectionRequest) ProtoMessage() {}

func (x *ReconnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectionRequest.ProtoReflect.Descriptor instead.
func (*ReconnectionRequest) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{6}
}

func (x *ReconnectionRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReconnectionRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type ReconnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccessful  bool                   `protobuf:"varint,1,opt,name=isSuccessful,proto3" json:"isSuccessful,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PrivateId     string                 `protobuf:"bytes,3,opt,name=privateId,proto3" json:"privateId,omitempty"`
	PublicId      string                 `protobuf:"bytes,4,opt,name=publicId,proto3" json:"publicId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectionResponse) Reset() {
	*x = ReconnectionResponse{}
	mi := &file_gamepacket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectionResponse) ProtoMessage() {}

func (x *ReconnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectionResponse.ProtoReflect.Descriptor instead.
func (*ReconnectionResponse) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{7}
}

func (x *ReconnectionResponse) GetIsSuccessful() bool {
	if x != nil {
		return x.IsSuccessful
	}
	return false
}

func (x *ReconnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReconnectionResponse) GetPrivateId() string {
	if x != nil {
		return x.PrivateId
	}
	return ""
}

func (x *ReconnectionResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type LobbyJoinBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=publicId,proto3" json:"publicId,omitempty"`
	Colorhex      string                 `protobuf:"bytes,2,opt,name=colorhex,proto3" json:"colorhex,omitempty"`
	Position      *ClientLobbyPosition   `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	IsLocalPlayer bool                   `protobuf:"varint,4,opt,name=isLocalPlayer,proto3" json:"isLocalPlayer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyJoinBroadcast) Reset() {
	*x = LobbyJoinBroadcast{}
	mi := &file_gamepacket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyJoinBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyJoinBroadcast) ProtoMessage() {}

func (x *LobbyJoinBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyJoinBroadcast.ProtoReflect.Descriptor instead.
func (*LobbyJoinBroadcast) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{8}
}

func (x *LobbyJoinBroadcast) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *LobbyJoinBroadcast) GetColorhex() string {
	if x != nil {
		return x.Colorhex
	}
	return ""
}

func (x *LobbyJoinBroadcast) GetPosition() *ClientLobbyPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *LobbyJoinBroadcast) GetIsLocalPlayer() bool {
	if x != nil {
		return x.IsLocalPlayer
	}
	return false
}

type ClientPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Timestamp     float32                `protobuf:"fixed32,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Velocity      *Velocity              `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPosition) Reset() {
	*x = ClientPosition{}
	mi := &file_gamepacket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPosition) ProtoMessage() {}

func (x *ClientPosition) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPosition.ProtoReflect.Descriptor instead.
func (*ClientPosition) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{9}
}

func (x *ClientPosition) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientPosition) GetTimestamp() float32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClientPosition) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ClientPosition) GetVelocity() *Velocity {
	if x != nil {
		return x.Velocity
	}
	return nil
}

type ClientLobbyPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientLobbyPosition) Reset() {
	*x = ClientLobbyPosition{}
	mi := &file_gamepacket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientLobbyPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientLobbyPosition) ProtoMessage() {}

func (x *ClientLobbyPosition) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientLobbyPosition.ProtoReflect.Descriptor instead.
func (*ClientLobbyPosition) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{10}
}

func (x *ClientLobbyPosition) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_gamepacket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{11}
}

func (x *Heartbeat) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_gamepacket_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatAck) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_gamepacket_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{13}
}

func (x *ServerStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerStatus) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_gamepacket_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{14}
}

func (x *Position) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Velocity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Velocity) Reset() {
	*x = Velocity{}
	mi := &file_gamepacket_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Velocity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Velocity) ProtoMessage() {}

func (x *Velocity) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Velocity.ProtoReflect.Descriptor instead.
func (*Velocity) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{15}
}

func (x *Velocity) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Velocity) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Velocity) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_gamepacket_proto protoreflect.FileDescriptor

const file_gamepacket_proto_rawDesc = "" +
	"\n" +
	"\x10gamepacket.proto\x12\n" +
	"gamepacket\"\xd4\a\n" +
	"\n" +
	"GamePacket\x12\x10\n" +
	"\x03Seq\x18\x01 \x01(\rR\x03Seq\x12H\n" +
	"\x10HandshakeRequest\x18\x02 \x01(\v2\x1c.gamepacket.HandshakeRequestR\x10HandshakeRequest\x12K\n" +
	"\x11HandshakeResponse\x18\x03 \x01(\v2\x1d.gamepacket.HandshakeResponseR\x11HandshakeResponse\x123\n" +
	"\tHeartbeat\x18\x04 \x01(\v2\x15.gamepacket.HeartbeatR\tHeartbeat\x12<\n" +
	"\fHeartbeatAck\x18\x05 \x01(\v2\x18.gamepacket.HeartbeatAckR\fHeartbeatAck\x12B\n" +
	"\x0eClientPosition\x18\x06 \x01(\v2\x1a.gamepacket.ClientPositionR\x0eClientPosition\x12N\n" +
	"\x12LobbyJoinBroadcast\x18\a \x01(\v2\x1e.gamepacket.LobbyJoinBroadcastR\x12LobbyJoinBroadcast\x12Q\n" +
	"\x13ClientLobbyPosition\x18\b \x01(\v2\x1f.gamepacket.ClientLobbyPositionR\x13ClientLobbyPosition\x12B\n" +
	"\x0eUsernamePrompt\x18\t \x01(\v2\x1a.gamepacket.UsernamePromptR\x0eUsernamePrompt\x12N\n" +
	"\x12UsernameSubmission\x18\n" +
	" \x01(\v2\x1e.gamepacket.UsernameSubmissionR\x12UsernameSubmission\x12H\n" +
	"\x10UsernameResponse\x18\v \x01(\v2\x1c.gamepacket.UsernameResponseR\x10UsernameResponse\x12Q\n" +
	"\x13ReconnectionRequest\x18\f \x01(\v2\x1f.gamepacket.ReconnectionRequestR\x13ReconnectionRequest\x12T\n" +
	"\x14ReconnectionResponse\x18\r \x01(\v2 .gamepacket.ReconnectionResponseR\x14ReconnectionResponse\x12<\n" +
	"\fServerStatus\x18c \x01(\v2\x18.gamepacket.ServerStatusR\fServerStatus\"2\n" +
	"\x10HandshakeRequest\x12\x1e\n" +
	"\n" +
	"clientName\x18\x01 \x01(\tR\n" +
	"clientName\"M\n" +
	"\x11HandshakeResponse\x12\x1c\n" +
	"\tprivateId\x18\x01 \x01(\tR\tprivateId\x12\x1a\n" +
	"\bpublicId\x18\x02 \x01(\tR\bpublicId\"*\n" +
	"\x0eUsernamePrompt\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"0\n" +
	"\x12UsernameSubmission\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x8a\x01\n" +
	"\x10UsernameResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"isAccepted\x18\x02 \x01(\bR\n" +
	"isAccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12 \n" +
	"\vsuggestions\x18\x04 \x03(\tR\vsuggestions\"U\n" +
	"\x13ReconnectionRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\"\n" +
	"\fsessionToken\x18\x02 \x01(\tR\fsessionToken\"\x8e\x01\n" +
	"\x14ReconnectionResponse\x12\"\n" +
	"\fisSuccessful\x18\x01 \x01(\bR\fisSuccessful\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tprivateId\x18\x03 \x01(\tR\tprivateId\x12\x1a\n" +
	"\bpublicId\x18\x04 \x01(\tR\bpublicId\"\xaf\x01\n" +
	"\x12LobbyJoinBroadcast\x12\x1a\n" +
	"\bpublicId\x18\x01 \x01(\tR\bpublicId\x12\x1a\n" +
	"\bcolorhex\x18\x02 \x01(\tR\bcolorhex\x12;\n" +
	"\bposition\x18\x03 \x01(\v2\x1f.gamepacket.ClientLobbyPositionR\bposition\x12$\n" +
	"\risLocalPlayer\x18\x04 \x01(\bR\risLocalPlayer\"\xae\x01\n" +
	"\x0eClientPosition\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x02R\ttimestamp\x120\n" +
	"\bposition\x18\x03 \x01(\v2\x14.gamepacket.PositionR\bposition\x120\n" +
	"\bvelocity\x18\x04 \x01(\v2\x14.gamepacket.VelocityR\bvelocity\"G\n" +
	"\x13ClientLobbyPosition\x120\n" +
	"\bposition\x18\x01 \x01(\v2\x14.gamepacket.PositionR\bposition\"'\n" +
	"\tHeartbeat\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\"*\n" +
	"\fHeartbeatAck\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\"D\n" +
	"\fServerStatus\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1a\n" +
	"\bclientId\x18\x02 \x01(\tR\bclientId\"4\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\"4\n" +
	"\bVelocity\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01zB\x15Z\x13gosocket/gamepacketb\x06proto3"

var (
	file_gamepacket_proto_rawDescOnce sync.Once
	file_gamepacket_proto_rawDescData []byte
)

func file_gamepacket_proto_rawDescGZIP() []byte {
	file_gamepacket_proto_rawDescOnce.Do(func() {
		file_gamepacket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamepacket_proto_rawDesc), len(file_gamepacket_proto_rawDesc)))
	})
	return file_gamepacket_proto_rawDescData
}

var file_gamepacket_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_gamepacket_proto_goTypes = []any{
	(*GamePacket)(nil),           // 0: gamepacket.GamePacket
	(*HandshakeRequest)(nil),     // 1: gamepacket.HandshakeRequest
	(*HandshakeResponse)(nil),    // 2: gamepacket.HandshakeResponse
	(*UsernamePrompt)(nil),       // 3: gamepacket.UsernamePrompt
	(*UsernameSubmission)(nil),   // 4: gamepacket.UsernameSubmission
	(*UsernameResponse)(nil),     // 5: gamepacket.UsernameResponse
	(*ReconnectionRequest)(nil),  // 6: gamepacket.ReconnectionRequest
	(*ReconnectionResponse)(nil), // 7: gamepacket.ReconnectionResponse
	(*LobbyJoinBroadcast)(nil),   // 8: gamepacket.LobbyJoinBroadcast
	(*ClientPosition)(nil),       // 9: gamepacket.ClientPosition
	(*ClientLobbyPosition)(nil),  // 10: gamepacket.ClientLobbyPosition
	(*Heartbeat)(nil),            // 11: gamepacket.Heartbeat
	(*HeartbeatAck)(nil),         // 12: gamepacket.HeartbeatAck
	(*ServerStatus)(nil),         // 13: gamepacket.ServerStatus
	(*Position)(nil),             // 14: gamepacket.Position
	(*Velocity)(nil),             // 15: gamepacket.Velocity
}
var file_gamepacket_proto_depIdxs = []int32{
	1,  // 0: gamepacket.GamePacket.HandshakeRequest:type_name -> gamepacket.HandshakeRequest
	2,  // 1: gamepacket.GamePacket.HandshakeResponse:type_name -> gamepacket.HandshakeResponse
	11, // 2: gamepacket.GamePacket.Heartbeat:type_name -> gamepacket.Heartbeat
	12, // 3: gamepacket.GamePacket.HeartbeatAck:type_name -> gamepacket.HeartbeatAck
	9,  // 4: gamepacket.GamePacket.ClientPosition:type_name -> gamepacket.ClientPosition
	8,  // 5: gamepacket.GamePacket.LobbyJoinBroadcast:type_name -> gamepacket.LobbyJoinBroadcast
	10, // 6: gamepacket.GamePacket.ClientLobbyPosition:type_name -> gamepacket.ClientLobbyPosition
	3,  // 7: gamepacket.GamePacket.UsernamePrompt:type_name -> gamepacket.UsernamePrompt
	4,  // 8: gamepacket.GamePacket.UsernameSubmission:type_name -> gamepacket.UsernameSubmission
	5,  // 9: gamepacket.GamePacket.UsernameResponse:type_name -> gamepacket.UsernameResponse
	6,  // 10: gamepacket.GamePacket.ReconnectionRequest:type_name -> gamepacket.ReconnectionRequest
	7,  // 11: gamepacket.GamePacket.ReconnectionResponse:type_name -> gamepacket.ReconnectionResponse
	13, // 12: gamepacket.GamePacket.ServerStatus:type_name -> gamepacket.ServerStatus
	10, // 13: gamepacket.LobbyJoinBroadcast.position:type_name -> gamepacket.ClientLobbyPosition
	14, // 14: gamepacket.ClientPosition.position:type_name -> gamepacket.Position
	15, // 15: gamepacket.ClientPosition.velocity:type_name -> gamepacket.Velocity
	14, // 16: gamepacket.ClientLobbyPosition.position:type_name -> gamepacket.Position
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_gamepacket_proto_init() }
func file_gamepacket_proto_init() {
	if File_gamepacket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamepacket_proto_rawDesc), len(file_gamepacket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamepacket_proto_goTypes,
		DependencyIndexes: file_gamepacket_proto_depIdxs,
		MessageInfos:      file_gamepacket_proto_msgTypes,
	}.Build()
	File_gamepacket_proto = out.File
	file_gamepacket_proto_goTypes = nil
	file_gamepacket_proto_depIdxs = nil
}
