// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: gamepacket.proto

package gamepacket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GamePacket struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Seq                uint32                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	HandshakeRequest   *HandshakeRequest      `protobuf:"bytes,2,opt,name=handshake_request,json=handshakeRequest,proto3" json:"handshake_request,omitempty"`
	HandshakeResponse  *HandshakeResponse     `protobuf:"bytes,3,opt,name=handshake_response,json=handshakeResponse,proto3" json:"handshake_response,omitempty"`
	Heartbeat          *Heartbeat             `protobuf:"bytes,4,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	HeartbeatAck       *HeartbeatAck          `protobuf:"bytes,5,opt,name=heartbeat_ack,json=heartbeatAck,proto3" json:"heartbeat_ack,omitempty"`
	ChatMessage        *ChatMessage           `protobuf:"bytes,6,opt,name=chat_message,json=chatMessage,proto3" json:"chat_message,omitempty"`
	LobbyJoinBroadcast *LobbyJoinBroadcast    `protobuf:"bytes,7,opt,name=lobby_join_broadcast,json=lobbyJoinBroadcast,proto3" json:"lobby_join_broadcast,omitempty"`
	ServerStatus       *ServerStatus          `protobuf:"bytes,99,opt,name=server_status,json=serverStatus,proto3" json:"server_status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GamePacket) Reset() {
	*x = GamePacket{}
	mi := &file_gamepacket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePacket) ProtoMessage() {}

func (x *GamePacket) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePacket.ProtoReflect.Descriptor instead.
func (*GamePacket) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{0}
}

func (x *GamePacket) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GamePacket) GetHandshakeRequest() *HandshakeRequest {
	if x != nil {
		return x.HandshakeRequest
	}
	return nil
}

func (x *GamePacket) GetHandshakeResponse() *HandshakeResponse {
	if x != nil {
		return x.HandshakeResponse
	}
	return nil
}

func (x *GamePacket) GetHeartbeat() *Heartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

func (x *GamePacket) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		return x.HeartbeatAck
	}
	return nil
}

func (x *GamePacket) GetChatMessage() *ChatMessage {
	if x != nil {
		return x.ChatMessage
	}
	return nil
}

func (x *GamePacket) GetLobbyJoinBroadcast() *LobbyJoinBroadcast {
	if x != nil {
		return x.LobbyJoinBroadcast
	}
	return nil
}

func (x *GamePacket) GetServerStatus() *ServerStatus {
	if x != nil {
		return x.ServerStatus
	}
	return nil
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    string                 `protobuf:"bytes,1,opt,name=clientName,proto3" json:"clientName,omitempty"` // optional nickname from client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_gamepacket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateId     string                 `protobuf:"bytes,1,opt,name=privateId,proto3" json:"privateId,omitempty"`
	PublicId      string                 `protobuf:"bytes,2,opt,name=publicId,proto3" json:"publicId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_gamepacket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetPrivateId() string {
	if x != nil {
		return x.PrivateId
	}
	return ""
}

func (x *HandshakeResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type LobbyJoinBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=publicId,proto3" json:"publicId,omitempty"`
	ColorHex      string                 `protobuf:"bytes,2,opt,name=colorHex,proto3" json:"colorHex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyJoinBroadcast) Reset() {
	*x = LobbyJoinBroadcast{}
	mi := &file_gamepacket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyJoinBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyJoinBroadcast) ProtoMessage() {}

func (x *LobbyJoinBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyJoinBroadcast.ProtoReflect.Descriptor instead.
func (*LobbyJoinBroadcast) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{3}
}

func (x *LobbyJoinBroadcast) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *LobbyJoinBroadcast) GetColorHex() string {
	if x != nil {
		return x.ColorHex
	}
	return ""
}

type ClientPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"` // who sent this
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPosition) Reset() {
	*x = ClientPosition{}
	mi := &file_gamepacket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPosition) ProtoMessage() {}

func (x *ClientPosition) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPosition.ProtoReflect.Descriptor instead.
func (*ClientPosition) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{4}
}

func (x *ClientPosition) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientPosition) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ClientPosition) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ClientPosition) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"` // who said it
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_gamepacket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{5}
}

func (x *ChatMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_gamepacket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_gamepacket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatAck) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_gamepacket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_gamepacket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_gamepacket_proto_rawDescGZIP(), []int{8}
}

func (x *ServerStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gamepacket_proto protoreflect.FileDescriptor

const file_gamepacket_proto_rawDesc = "" +
	"\n" +
	"\x10gamepacket.proto\x12\n" +
	"gamepacket\"\xf8\x03\n" +
	"\n" +
	"GamePacket\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\rR\x03seq\x12I\n" +
	"\x11handshake_request\x18\x02 \x01(\v2\x1c.gamepacket.HandshakeRequestR\x10handshakeRequest\x12L\n" +
	"\x12handshake_response\x18\x03 \x01(\v2\x1d.gamepacket.HandshakeResponseR\x11handshakeResponse\x123\n" +
	"\theartbeat\x18\x04 \x01(\v2\x15.gamepacket.HeartbeatR\theartbeat\x12=\n" +
	"\rheartbeat_ack\x18\x05 \x01(\v2\x18.gamepacket.HeartbeatAckR\fheartbeatAck\x12:\n" +
	"\fchat_message\x18\x06 \x01(\v2\x17.gamepacket.ChatMessageR\vchatMessage\x12P\n" +
	"\x14lobby_join_broadcast\x18\a \x01(\v2\x1e.gamepacket.LobbyJoinBroadcastR\x12lobbyJoinBroadcast\x12=\n" +
	"\rserver_status\x18c \x01(\v2\x18.gamepacket.ServerStatusR\fserverStatus\"2\n" +
	"\x10HandshakeRequest\x12\x1e\n" +
	"\n" +
	"clientName\x18\x01 \x01(\tR\n" +
	"clientName\"M\n" +
	"\x11HandshakeResponse\x12\x1c\n" +
	"\tprivateId\x18\x01 \x01(\tR\tprivateId\x12\x1a\n" +
	"\bpublicId\x18\x02 \x01(\tR\bpublicId\"L\n" +
	"\x12LobbyJoinBroadcast\x12\x1a\n" +
	"\bpublicId\x18\x01 \x01(\tR\bpublicId\x12\x1a\n" +
	"\bcolorHex\x18\x02 \x01(\tR\bcolorHex\"V\n" +
	"\x0eClientPosition\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\"C\n" +
	"\vChatMessage\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\tHeartbeat\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\"+\n" +
	"\fHeartbeatAck\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"(\n" +
	"\fServerStatus\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\x15Z\x13gosocket/gamepacketb\x06proto3"

var (
	file_gamepacket_proto_rawDescOnce sync.Once
	file_gamepacket_proto_rawDescData []byte
)

func file_gamepacket_proto_rawDescGZIP() []byte {
	file_gamepacket_proto_rawDescOnce.Do(func() {
		file_gamepacket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamepacket_proto_rawDesc), len(file_gamepacket_proto_rawDesc)))
	})
	return file_gamepacket_proto_rawDescData
}

var file_gamepacket_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gamepacket_proto_goTypes = []any{
	(*GamePacket)(nil),         // 0: gamepacket.GamePacket
	(*HandshakeRequest)(nil),   // 1: gamepacket.HandshakeRequest
	(*HandshakeResponse)(nil),  // 2: gamepacket.HandshakeResponse
	(*LobbyJoinBroadcast)(nil), // 3: gamepacket.LobbyJoinBroadcast
	(*ClientPosition)(nil),     // 4: gamepacket.ClientPosition
	(*ChatMessage)(nil),        // 5: gamepacket.ChatMessage
	(*Heartbeat)(nil),          // 6: gamepacket.Heartbeat
	(*HeartbeatAck)(nil),       // 7: gamepacket.HeartbeatAck
	(*ServerStatus)(nil),       // 8: gamepacket.ServerStatus
}
var file_gamepacket_proto_depIdxs = []int32{
	1, // 0: gamepacket.GamePacket.handshake_request:type_name -> gamepacket.HandshakeRequest
	2, // 1: gamepacket.GamePacket.handshake_response:type_name -> gamepacket.HandshakeResponse
	6, // 2: gamepacket.GamePacket.heartbeat:type_name -> gamepacket.Heartbeat
	7, // 3: gamepacket.GamePacket.heartbeat_ack:type_name -> gamepacket.HeartbeatAck
	5, // 4: gamepacket.GamePacket.chat_message:type_name -> gamepacket.ChatMessage
	3, // 5: gamepacket.GamePacket.lobby_join_broadcast:type_name -> gamepacket.LobbyJoinBroadcast
	8, // 6: gamepacket.GamePacket.server_status:type_name -> gamepacket.ServerStatus
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_gamepacket_proto_init() }
func file_gamepacket_proto_init() {
	if File_gamepacket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamepacket_proto_rawDesc), len(file_gamepacket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamepacket_proto_goTypes,
		DependencyIndexes: file_gamepacket_proto_depIdxs,
		MessageInfos:      file_gamepacket_proto_msgTypes,
	}.Build()
	File_gamepacket_proto = out.File
	file_gamepacket_proto_goTypes = nil
	file_gamepacket_proto_depIdxs = nil
}
